name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 6
        uses: actions/setup-java@v2
        with:
          java-version: '6'
          distribution: 'oracle'
          architecture: 'x32'
      - name: Build with Gradle
        run: ./gradlew build test
